id = "jam"
name = "Jam"
description = "Jam programming language support for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Raphael Amorim <rapha850@gmail.com>"]
repository = "https://github.com/tri-berry/tree-sitter-jam"

[grammars.jam]
repository = "https://github.com/tri-berry/tree-sitter-jam"
rev = "05229ae0a4f9d261818f4939c72dcb638df522cb"
